[package]
name = "zapjs-website-native"
version = "0.1.0"
edition = "2021"
[workspace]
[lib]
crate-type = ["cdylib"]
[dependencies]
napi = { version = "=3.13.0", default-features = false, features = ["napi8", "tokio_rt", "dyn-symbols"] }
napi-derive = "=3.6.9"
zap-native = { path = "../node_modules/@zap-js/client/dist/native/rust" }
[build-dependencies]
napi-build = "=2.5.0"
